  var nodes = new vis.DataSet([
 {
   "id": 1,
   "label": "Paul Otlet",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliographie",
   "discipline_en": "Bibliography",
   "description": "Paul Otlet est la tête pensante du Mundaneum, ce lieu de rassemblement de la connaissance qui héberge notamment le Répertoire Bibliographique Universel. Il a consacré toute sa vie à développer cette institution et le réseau de personnnalités et d'institutions qui l'entourent.\n",
   "description_en": "Paul Otlet is the mind behind the Mundaneum, a milestone in the history of data collection, which is host to the Répertoire Bibliographique Universel (National Bibliographic Directory). He spent his life developping this institution and the network of people and institutions surrounding it.",
   "image": "img/POtlet.png",
   "group": "otlet",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Fondateur du Mundaneum",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Paul_Otlet",
   "date_naissance": "23/08/1868",
   "date_mort": "10/12/1944",
   "gender": "Homme"
 },
 {
   "id": 2,
   "label": "Henri La Fontaine",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Pacifisme / Bibliographie",
   "discipline_en": "Pacifism / Bibliography",
   "description": "Henri La Fontaine est un homme politique socialiste. En 1913, il obtient le Prix Nobel de la Paix. Avec Paul Otlet, il collabore à un vaste réseau intellectuel en faveur de la connaissance et milite autour d'associations internationales pour la paix et pour les droits des femmes.",
   "description_en": "Henri La Fontaine was a socialist politician. He received the Nobel Prize for Peace in 1913. With the help of Paul Otlet, he helped creating a large network of knowledge. He was famous internationally for being a leader of the peace and women's rights movements.",
   "image": "img/HLaFontaine.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Co-Fondateur du Mundaneum",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Henri_La_Fontaine",
   "date_naissance": "22/4/1854",
   "date_mort": "14/05/1943",
   "gender": "Homme"
 },
 {
   "id": 3,
   "label": "Ernest Solvay",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Industrie / Sociologie",
   "discipline_en": "Chemistry / Sociology",
   "description": "Entrepreneur, chimiste et inventeur. La réussite d'Ernest Solvay est due à fabrication de la soude. Il investit sa fortune dans la recherche scientifique et notamment dans les congrès internationaux de Physique et de Chimie.",
   "description_en": "Ernest Solvay was a chemist and inventor, His success was due to the invention of a major industrial process for the production of sodium carbonate. He invested his fortune in scientific research and in the organisation of many international science congress.",
   "image": "img/ESolvay.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Ernest_Solvay",
   "date_naissance": "16/04/1838",
   "date_mort": "26/05/1822",
   "gender": "Homme"
 },
 {
   "id": 4,
   "label": "Ovide Decroly",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Pédagogie / Médecine / Sociologie",
   "discipline_en": "Pedagogy / Medecine / Siocology",
   "description": "Pédagogue et médecin, Ovide Decroly s'intéresse aux troubles de l'enfant. Membre du mouvement d'Education nouvelle, il développe une approche psychologique inédite.",
   "description_en": "Ovide Decroly was a Belgian teacher and psychologist. He mainly worked with mentally handiccaped children, and created a new pedagogical approach named the \"Decroly plan\"",
   "image": "img/ODecroly.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Ovide_Decroly",
   "date_naissance": "23/07/1871",
   "date_mort": "12/09/1932",
   "gender": "Homme"
 },
 {
   "id": 5,
   "label": "Mundaneum",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Coopération",
   "discipline_en": "",
   "description": "Le Mundaneum est le centre intellectuel créé en 1920 au Cinquantenaire (Bruxelles). Ses activités de coopération internationale sont marquées par l'université internationale et l'encyclopédie didactique d'un nouveau genre.",
   "description_en": "The Mundaneum is a non-profit organisation created in 1910 in Brussels. It aimed to gather together all the world's knowledge and classify it according to a system they developed called the Universal Decimal Classification.",
   "image": "img/Mundaneum.png",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Mundaneum",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Mundaneum",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 6,
   "label": "Institut International de Bibliographie",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliographie",
   "discipline_en": "Bibliography",
   "description": "l'IIB débute son travail sur la bibliographie dès 1895. Le Répertoire Bibliographique universel constitue un outil intellectuel de partage de la connaissance et de recherche (Google de papier).",
   "description_en": "The IIB started started working on bibliography in 1895. The Répertoire Bibliographique Universel (National Bibliographic Directory) was a major tool for the sharing of knowledge and research, known today as the Google made of paper.",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Mundaneum",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Office_international_de_bibliographie_-_Institut_international_de_bibliographie",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 7,
   "label": "Edmond Picard",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Droit / Encyclopédie / Art / Université",
   "discipline_en": "Law / Encyclopedia / Art / University",
   "description": "Figure imposante du barreau, ce juriste met au point une encyclopédie de la jurisprudence belge. En politique, il se bat pour le suffrage universel et devient sénateur socialiste.",
   "description_en": "This important jurist wrote an encyclopedia about Belgian jurisprudence. He got himself involved in politics where he fought for the universal suffrage and became a socialist senator.",
   "image": "img/EPicard.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Edmond_Picard",
   "date_naissance": "15/12/1836",
   "date_mort": "12/02/1924",
   "gender": "Homme"
 },
 {
   "id": 8,
   "label": "Patrick Geddes",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Ecosse",
   "nationalite_en": "Scottish",
   "discipline": "Architecture",
   "discipline_en": "Architecture",
   "description": "Théoricien majeur de l'urbanisme, Patrick Geddes introduit la notion d'environnement dans le développement des villes. Son collège des écossais est une tentative de cité universitaire internationale. Il échange pendant des années avec Paul Otlet en langue française.",
   "description_en": "Patrick Geddes is known for his innovative thinking in the field of urban planning. He introduced the concept of environment in urban development. He founded the Scots College, which was a try at an an international students’ Center. As a francophile, he maintained a correspondance with Paul Otlet for years.",
   "image": "img/PGeddes.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Patrick_Geddes",
   "date_naissance": "02/10/1854",
   "date_mort": "17/04/1932",
   "gender": "Homme"
 },
 {
   "id": 9,
   "label": "Marie Popelin",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Féminisme",
   "discipline_en": "Feminism",
   "description": "Diplomée en droit, Marie Popelin crée en 1892 la première association féministe belge, la ligue du droit des femmes. Son action est déterminante pour la revendication de nouveaux droits.",
   "description_en": "Marie Popelin was a Belgian lawyer and early feminist political campaigner. She created the first ever Belgian feminist association. Her actions are major in the achievements of gender equality.",
   "image": "img/MPopelin.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Amie de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Marie_Popelin",
   "date_naissance": "16/12/1846",
   "date_mort": "05/06/1913",
   "gender": "Femme"
 },
 {
   "id": 10,
   "label": "Hippolyte Sébert",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Bibliographie / Langue universelle / Esperanto / Photographie",
   "discipline_en": "Bibliography / Universal Language / Esperanto / Photography",
   "description": "Après une carrière militaire, Hyppolite Sébert entame une deuxième vie, consacrée aux sciences. Figure incontournable de l'esperanto, il anime le bureau bibliographique de Paris depuis 1898.",
   "description_en": "After being in the military, Hyppolite Sebert dedicates his life to sciences. He was a major figure in the development of esperanto. He also worked closely with the Bibliography Bureau in Paris.",
   "image": "img/HSebert.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Hippolyte_Sebert",
   "date_naissance": "30/01/1839",
   "date_mort": "23/01/1930",
   "gender": "Homme"
 },
 {
   "id": 11,
   "label": "Léonie La Fontaine",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Féminisme / Bibliographie",
   "discipline_en": "Feminism / BIbliography",
   "description": "Féministe et pacifiste, Léonie La Fontaine se distingue par son engagement dans des associations belges et internationales. Elle s'engage dans la ligue et le CNFB",
   "description_en": "Léonie La Fontaine was a Belgian pioneering feminist and pacifist. Active in the international feminism struggle, she was a member of the Belgian League for the Rights of Women.",
   "image": "img/LLFontaine.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Amie de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/L%C3%A9onie_La_Fontaine",
   "date_naissance": "02/10/1857",
   "date_mort": "26/01/1949",
   "gender": "Femme"
 },
 {
   "id": 12,
   "label": "Andrew Carnegie",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "USA",
   "nationalite_en": "USA",
   "discipline": "Pacifisme / Bibliothèque",
   "discipline_en": "Pacifism / Library",
   "description": "Magnat de l'industrie, Andrew Carnegie consacrera sa fortune à de nombreuses fondations philanthropiques comme celle pour la paix internationale ou celles dédiées aux bibliothèques dans le monde.",
   "description_en": "Andrew Carnegie was a business magnate and philanthropist. He will dedicate a large part of his fortune in various philantropic associations, such as the International Peace Association, or various associations for the preservation of libraries.",
   "image": "img/ACarnegie.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Andrew_Carnegie",
   "date_naissance": "25/11/1835",
   "date_mort": "11/08/1919",
   "gender": "Homme"
 },
 {
   "id": 13,
   "label": "Melvil Dewey",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "USA",
   "nationalite_en": "USA",
   "discipline": "Classification / CDU",
   "discipline_en": "Library Classification / UDC",
   "description": "Mevil Dewey est un bibliothécaire américain. Avec la classification décimale, il révolutionne l'organisation des bibliothèques aux Etats-Unis et crée des structures professionnels d'apprentissage pour les bibliotécaires. Il créé notamment l'ALA (American Library Association) ainsi que le Library Journal",
   "description_en": "Melvil Dewey was an American librarian and educator, inventor of the Dewey Decimal system of library classification. He is the founder of the American Library Association and the Library Journal.",
   "image": "img/MDewey.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Melvil_Dewey",
   "date_naissance": "10/12/1851",
   "date_mort": "26/12/1931",
   "gender": "Homme"
 },
 {
   "id": 14,
   "label": "Herbert Haviland Field",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Suisse",
   "nationalite_en": "Swiss",
   "discipline": "Bibliographie / Zoologie",
   "discipline_en": "Bibliography / Zoology",
   "description": "Fondateur du Concilium Bibliographicum, Field publie les bibliographies de zoologie et de physiologie. Pour cela, il améliore la classification de Dewey dans ces matières.",
   "description_en": "Field founded the Concilium Bibliophraghicum, he published various bibliographies in the field of zoology and physiology. His work is heavily inspired by the Dewey classification.",
   "image": "img/HHaviland.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 15,
   "label": "Robert Goldschmidt",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Chimie / Radio / Electricité",
   "discipline_en": "Chemistry / Radio / Electricity",
   "description": "Docteur en sciences, Robert Goldschmidt se distingue pour ses innovations techniques avec le dirigeable, la télégraphie ou la TSF. Il met au point le procédé du microfilm. Avec Otlet, il travaille à un dispositif de bibliothèque mobile reposant sur des ouvrages microfichés.",
   "description_en": "Robert B. Goldschmidt was a Belgian chemist, physicist, and engineer who first proposed the idea of standardized microfiche (microfilm). He worked with Paul Otlet on the project of a mobile library using the microfiche technology.",
   "image": "img/RGoldschmidt.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Robert_Goldschmidt",
   "date_naissance": "04/05/1877",
   "date_mort": "28/05/1935",
   "gender": "Homme"
 },
 {
   "id": 16,
   "label": "Otto Neurath",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Autriche",
   "nationalite_en": "Austrian",
   "discipline": "Musées / Sciences Sociales",
   "discipline_en": "Museums / Social Sciences",
   "description": "Philosophe et sociologue, Otto Neurath crée un musée socio-économique à Vienne. Il développe un langage de représentation quantatif des données, l'Isotype. Il poursuit avec Otlet le réseau Mundaneum. Les deux hommes fusionnent même leurs idées dans le projet NOP.",
   "description_en": "Otto Neurath was an Austrian philosopher and sociologist. Neurath created Isotype, a symbolic way of representing quantitative information via easily interpretable icons. He worked closely with Paul Otlet on the Mundaneum.",
   "image": "img/ONeurath.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Otto_Neurath",
   "date_naissance": "10/12/1882",
   "date_mort": "22/12/1945",
   "gender": "Homme"
 },
 {
   "id": 17,
   "label": "Ernest De Potter",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Photographie",
   "discipline_en": "Photography",
   "description": "Amateur belge de photographies, Ernest de Potter se consacre à ce média et crée la revue internationale de Photographie ainsi que l'Institut International de Photographie.",
   "description_en": "This Belgian photographer created the International Photography Journal, as well as the Internation Institute of Photography",
   "image": "",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 18,
   "label": "Cyrille Van Overbergh",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Art / Sociologie / Culture",
   "discipline_en": "Art / Sociology / Culture",
   "description": "Ce haut fonctionnaire de l'Etat au sein de l'administration de l'enseignement, des sciences et des lettres, effectue une carrière politique pour le parti chrétien démocrate et devient sénateur. Il créa la société belge de sociologie et fut directeur du bureau international d'Ethnographie.",
   "description_en": "This Belgian politician became a senator. He founded the Belgian Society of Sociology, as well as the Internal Bureau of Ethnography",
   "image": "img/CVOverbergh.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 19,
   "label": "Hector Denis",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Université",
   "discipline_en": "Sociology / University",
   "description": "Recteur de l'Université et Membre de la société des études sociales et politiques, Hector Denis déclenche une grave crise universitaire en invitant l'anarchiste Elisée Reclus. Une université nouvelle se crée autour des partisans d'une réforme sociale.",
   "description_en": "While being a university rector, Hector Denis started a university crisis by spreading anarchist ideas. A new university is created around him advocating a social reform.",
   "image": "img/HDenis.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Hector_Denis",
   "date_naissance": "29/04/1842",
   "date_mort": "10/05/1913",
   "gender": "Homme"
 },
 {
   "id": 20,
   "label": "Baron Edouard Descamps",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliographie / Pacifisme / Culture",
   "discipline_en": "Bibliography / Pacifism / Culture",
   "description": "Homme politique catholique belge, Il est pacifiste et anti-esclavagiste. En 1907, il obtient le premier portefeuille de la culture en Belgique (Ministère des sciences et des Arts).",
   "description_en": "This Catholic Belgian politician was a pacifist and anti-slavery.",
   "image": "img/EDescamps.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/%C3%89douard_Descamps",
   "date_naissance": "27/08/1847",
   "date_mort": "17/12/1933",
   "gender": "Homme"
 },
 {
   "id": 21,
   "label": "Georges Lecointe",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Géographie",
   "discipline_en": "Geography",
   "description": "Georges lecointe est membre de l'expédition Polaire au côté d'Adrien de Gerlache sur le Belgica. Il devient directeur de la section astronomie de l'Observatoire d'Uccle.",
   "description_en": "George Lecointe is one of the member of the Polar expedition on the Belgica. He became the director of the astronomy branch of the Uccle observatory.",
   "image": "img/GLecointe.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Georges_Lecointe_(officier)",
   "date_naissance": "29/04/1869",
   "date_mort": "27/05/1929",
   "gender": "Homme"
 },
 {
   "id": 22,
   "label": "Octave Maus",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Art / Presse",
   "discipline_en": "Art / Press",
   "description": "Avocat et critique d'art, Octave Maus participe au mouvement de la Libre-Esthétique. Aux côtés de Vandervelde et de Picard, il anime la revue l'Art Moderne.",
   "description_en": "This lawyer and art critic participated in the free-aesthetic movement. He directed, with Vendervelde and Picard, the Art Moderne magazine.",
   "image": "img/OMaus.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Octave_Maus",
   "date_naissance": "12/06/1856",
   "date_mort": "26/11/1919",
   "gender": "Homme"
 },
 {
   "id": 23,
   "label": "Emile Verhaeren",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Art / Littérature",
   "discipline_en": "Art / Litterature",
   "description": "Poète et critique d'art passionné, Emile Verhaeren atteint la renommée mondiale pour son avant-garde et son expressionnisme. Son oeuvre est traduite et discutée de son vivant.",
   "description_en": "This poet and art critic gained international fame for his avant-garde and impressionist art. ",
   "image": "img/EVerhaeren.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/%C3%89mile_Verhaeren",
   "date_naissance": "21/05/1855",
   "date_mort": "27/11/1916",
   "gender": "Homme"
 },
 {
   "id": 24,
   "label": "Gaston Mertens",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Presse",
   "discipline_en": "Press",
   "description": "Membre de l'Union de la presse périodique belge, Gaston Mertens est un collectionneur de journaux. Il collabore activement à la création du Musée de la Presse",
   "description_en": "This newpaper collector became a member of the Belgian Press Union. He helped in the creation of the Press Museum.",
   "image": "",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 25,
   "label": "Léon Losseau",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliographie / Droit",
   "discipline_en": "Bibliography / Law",
   "description": "Avocat, bibliophile, collectionneur de médailles, Léon Losseau est l'auteur d'une formidable encyclopédie dédiée au Hainaut.",
   "description_en": "This lawyer and bibliography enthusiast is the author of an encyclopedia about the Hainaut Province.",
   "image": "img/LLosseau.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/L%C3%A9on_Losseau",
   "date_naissance": "09/03/1869",
   "date_mort": "07/08/1949",
   "gender": "Homme"
 },
 {
   "id": 26,
   "label": "Charles Buls",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Enseignement",
   "discipline_en": "Sociology / Education",
   "description": "Bourgmestre de la ville de Bruxelles, Charles Buls est un ardent défenseur du patrimoine. Il crée la ligue de l'enseignement.",
   "description_en": "This Bruxellois politician is the founder of the Ligue de l'Enseignement",
   "image": "img/CBuls.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Charles_Buls",
   "date_naissance": "13/08/1837",
   "date_mort": "13/07/1914",
   "gender": "Homme"
 },
 {
   "id": 27,
   "label": "Auguste Beernaert",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Pacifisme / Politique",
   "discipline_en": "Pacifism / Politics",
   "description": "Homme politique catholique, Auguste Beernaert reçoit le Prix nobel de la paix en 1909. Il représente la Belgique au premier Congrès de la Paix à La Haye en 1899.",
   "description_en": "This Catholic politician gets a Nobel Prize for peace in 1909. He represents Belgium at the first peace congress of La Haye in 1899.",
   "image": "img/ABeernaert.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Auguste_Beernaert",
   "date_naissance": "26/07/1829",
   "date_mort": "06/10/1912",
   "gender": "Homme"
 },
 {
   "id": 28,
   "label": "Léon Wouters",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliothèque",
   "discipline_en": "Library",
   "description": "Entré au service de l'IIB à 21 ans (1901), Léon Wouters publie notamment quelques ouvrages sur la CDU et l'Institut. Il est responsable de la Bibliothèque collective des sociétés savantes.",
   "description_en": "Entré au service de l'IIB à 21 ans (1901), Léon Wouters publie notamment quelques ouvrages sur la CDU et l'Institut. Il est responsable de la Bibliothèque collective des sociétés savantes. Léon Wouters started working for the International Federation for Information and Documentation at 20 years old. He's in charge of the collective library for the learned societies.",
   "image": "",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 29,
   "label": "Louis Masure",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Bibliographie",
   "discipline_en": "Bibliography",
   "description": "Louis Masure devient en 1896 collaborateur de l'Institut International de Bibliographie. En tant que secrétaire, il réalise un travail important auprès de Paul Otlet et Henri La Fontaine: gestion du personnel et suivi des travaux.",
   "description_en": "Louis Masure starts working for the International Federation for Information and Documentation in 1896 where he works closely with Otlet and La Fontaine",
   "image": "",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 30,
   "label": "Paul Héger",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Physiologie / Sociologie",
   "discipline_en": "Physiology / Sociology",
   "description": "Médecin précurseur, Paul Héger développe la médecine expérimentale. Son travail lui vaut le soutien de l'industriel Ernest Solvay pour la création de l'Institut de Physiologie.",
   "description_en": "This experimental doctor got the support of Ernest Solvay for creating the Institute of Physiology.",
   "image": "img/PHeger.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Paul_H%C3%A9ger",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 31,
   "label": "Alfred Hermann Fried",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Autriche",
   "nationalite_en": "Austrian",
   "discipline": "Pacifisme",
   "discipline_en": "Pacifism",
   "description": "Collaborateur avec Bertha Von Suttner, membre de l'Institut international de la paix (Monaco), Alfred Hermann Fried milite pour la paix.",
   "description_en": "This member of the International Institute of Peace acts closely with Bertha Von Suttner in favor of Peace",
   "image": "img/AHFried.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Alfred_Hermann_Fried",
   "date_naissance": "11/10/1864",
   "date_mort": "05/05/1921",
   "gender": "Homme"
 },
 {
   "id": 32,
   "label": "Jules Siegfried",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Pacifisme / Féminisme / Enseignement",
   "discipline_en": "Pacifism / Feminism / Teaching",
   "description": "Jules Siegfried est un homme politique français. Il fait passer une loi qui favorise l'habitation à bon marché.",
   "description_en": "This French politician passes a bill in favor of cheaper housing",
   "image": "img/JSiegfried.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Jules_Siegfried",
   "date_naissance": "12/02/1837",
   "date_mort": "26/09/1922",
   "gender": "Homme"
 },
 {
   "id": 33,
   "label": "Gaston Moch",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Pacifisme / Langue internationale",
   "discipline_en": "Pacifism / International Language",
   "description": "Après une carrière dans l'armée française, Gaston Moch se consacre au pacifisme. Espérantiste, il s'engage dans la défense des droits de l'homme.",
   "description_en": "After being in the military, this pacifist works for favorising Human Rights.",
   "image": "img/GMoch.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Gaston_Moch",
   "date_naissance": "05/03/1859",
   "date_mort": "03/07/1935",
   "gender": "Homme"
 },
 {
   "id": 34,
   "label": "Frédéric Passy",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Pacifisme / Sociologie",
   "discipline_en": "Pacifism / Sociology",
   "description": "Cet homme politique français est un pionnier du mouvement pacifiste. Il est lauréat du Prix Nobel de la paix en 1901.",
   "description_en": "This French Politician is a pionneer of the pacifist movement. He obtains a Nobel Prize for Peace in 1901",
   "image": "img/FPassy.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Passy",
   "date_naissance": "20/05/1822",
   "date_mort": "12/06/1912",
   "gender": "Homme"
 },
 {
   "id": 35,
   "label": "Bertha vonSuttner",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Autriche",
   "nationalite_en": "Austrian",
   "discipline": "Pacifisme",
   "discipline_en": "Pacifism",
   "description": "Bertha Von Suttner, pacifiste autrichienne, se fait connaître grâce à son roman Bas les Armes. Elle reçoit le prix nobel de la paix en 1905.",
   "description_en": "Bertha Von Suttner, pacifiste autrichienne, se fait connaître grâce à son roman Bas les Armes. Elle reçoit le prix nobel de la paix en 1905. This Austrian pacifist gets international fame for her book \"Bas les Armes\". She obtains a Nobel Prize for peace in 1905.",
   "image": "img/BVSuttner.png",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaboratrice",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Bertha_von_Suttner",
   "date_naissance": "09/06/1843",
   "date_mort": "21/06/1914",
   "gender": "Homme"
 },
 {
   "id": 36,
   "label": "Jacques Novicow",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Russie",
   "nationalite_en": "Russian",
   "discipline": "Pacifisme / Sociologie",
   "discipline_en": "Pacifism / Sociology",
   "description": "Sociologue et pacifiste russe, Jacques Novicow défend l'idée d'une fédération européenne.",
   "description_en": "This Russian sociologist and pacifist works in favor of a European Federation",
   "image": "",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Jacques_Novicow",
   "date_naissance": "29/09/1849",
   "date_mort": "21/05/1912",
   "gender": "Homme"
 },
 {
   "id": 37,
   "label": "Louis Couturat",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Langue internationale / Philosophie / Mathématique",
   "discipline_en": "Universal Language / Philosophy",
   "description": "Mathématicien et philosophe français, Louis Couturat est un pacifiste engagé dans la défense d'une langue internationale, l'IDO",
   "description_en": "This French philoopher and mathematician works in favor of an international language: The IDO",
   "image": "img/LCouturat.png",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Louis_Couturat",
   "date_naissance": "17/01/1868",
   "date_mort": "03/08/1914",
   "gender": "Homme"
 },
 {
   "id": 38,
   "label": "Madame Jules Siegfried",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Féminisme",
   "discipline_en": "Feminism",
   "description": "Féministe au sein du Conseil des femmes françaises, Julie Siegfried s'intéresse d'abord à la question de l'éducation avant de promouvoir le vote des femmes avec l'aide de son époux, le parlementaire Jules Siegfried.",
   "description_en": "This French feminist works in favor of education. She will also be an advocate of the women's suffrage with her husband Jules Siegfried",
   "image": "img/MJSiegfried.png",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaboratrice",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Julie_Siegfried",
   "date_naissance": "13/03/1848",
   "date_mort": "28/05/1922",
   "gender": "Femme"
 },
 {
   "id": 39,
   "label": "Adolphe Ferrière",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Suisse",
   "nationalite_en": "Swiss",
   "discipline": "Pédagogie",
   "discipline_en": "Education",
   "description": "Pédagogue suisse, il développe le mouvement d'une école nouvelle",
   "description_en": "This Swiss pedagogue wanted to reform education",
   "image": "img/AFerriere.png",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Adolphe_Ferri%C3%A8re",
   "date_naissance": "30/08/1879",
   "date_mort": "16/06/1960",
   "gender": "Homme"
 },
 {
   "id": 40,
   "label": "Octave Van Rysselberghe",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Architecture",
   "discipline_en": "Architecture",
   "description": "Architecte belge du mouvement Art Nouveau, il s'associe à Henry Vandevelde au début de sa carrière. Il réalise entre autre l'Observatoire d'Uccle.",
   "description_en": "This Belgian architect is inspired by the Art Nouveau movement. He mainly deisgned the Uccle Observatory with Henry Vandevelde",
   "image": "",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Octave_van_Rysselberghe",
   "date_naissance": "22/07/1855",
   "date_mort": "30/03/1929",
   "gender": "Homme"
 },
 {
   "id": 41,
   "label": "Charles Sury",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Bibliothèque / Féminisme",
   "discipline_en": "Sociology / Library / Feminism",
   "description": "Bibliothécaire au sein de l'IIB, Charles Sury rejoint la bibliothèque de l'Université.",
   "description_en": "Charles Sury was the librarian of the International Federation for Information and Documentation",
   "image": "",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 42,
   "label": "Emile Vandervelde",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Socialisme",
   "discipline_en": "Sociology / Socialism",
   "description": "Emile Vandervelde est le patron du parti socialiste belge (POB). Le suffrage universel et la démocratie sociale caractérisent sa politique.",
   "description_en": "Emile Vandervelde was the director of the Belgian Socialist Party. He was an advocate of the women's suffrage.",
   "image": "img/EVandervelde.png",
   "group": "collaborateurs",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Collaborateur",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/%C3%89mile_Vandervelde",
   "date_naissance": "25/01/1856",
   "date_mort": "27/12/1938",
   "gender": "Homme"
 },
 {
   "id": 43,
   "label": "Emile Waxweiler",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Pédagogie",
   "discipline_en": "Sociology / Education",
   "description": "Fondateur et directeur de l'Institut de Sociologie, Emile Waxweiler est un statisticien qui se spécialise dans la sociologie fonctionnelle.",
   "description_en": "Emile Waxweiler was the founder of the Sociology Institute in Belgium. He specialises in functional sociology.",
   "image": "img/EWaxweiler.png",
   "group": "contemporains",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Contemporain",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/%C3%89mile_Waxweiler",
   "date_naissance": "22/05/1867",
   "date_mort": "26/06/1916",
   "gender": "Homme"
 },
 {
   "id": 44,
   "label": "Charles Richet",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française",
   "nationalite_en": "French",
   "discipline": "Physiologie / Bibliographie",
   "discipline_en": "Physiology / Library",
   "description": "Pacifiste et patriote, Charles Richet est un physiologue français qui obtient le prix nobel de médecine en 1913. Il participe à la CDU. Certains de ses travaux sont jugés désormais eugénistes. Il effectue également des recherches sur le paranormal.",
   "description_en": "Charles Richet was a French Psychologist, he won the Nobel Prize in Medicine in 1913. Some of his work is now labelled as eugenicist. He also researched on paranormal activities.",
   "image": "img/CRichet.png",
   "group": "contemporains",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Contemporain",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Charles_Richet",
   "date_naissance": "26/08/1850",
   "date_mort": "03/12/1935",
   "gender": "Homme"
 },
 {
   "id": 45,
   "label": "Josepha Ioteyko",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Pologne",
   "nationalite_en": "Polish",
   "discipline": "Pédagogie / Physiologie",
   "discipline_en": "Education / Physiology",
   "description": "Chef de travaux en psycho-physiologie, Josepha Ioteyko fonde l'Institut de Pédologie après le congrès de 1911.",
   "description_en": "Description traduite",
   "image": "img/JIoteyko.png",
   "group": "contemporains",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Contemporain",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Femme"
 },
 {
   "id": 46,
   "label": "Le Corbusier",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Française/Suisse",
   "nationalite_en": "French/Swiss",
   "discipline": "Architecture",
   "discipline_en": "Architecture",
   "description": "Charles-Edouard Jeanneret, dit le Corbusier, est un architecte représentatif du mouvement moderne. Son style est largement dominé par le fonctionnalisme. Il échange avec Otlet au sujet des projets de cité mondiale. Le projet est d'ailleurs un temps envisagé du côté de Genève.",
   "description_en": "Le Corbusier is an architect of the modern movement, whose style is driven by functional design. He worked closely with Paul Otlet regarding the World City project.",
   "image": "img/LCorbusier.png",
   "group": "contemporains",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Contemporain",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Le_Corbusier",
   "date_naissance": "06/10/1887",
   "date_mort": "27/08/1965",
   "gender": "Homme"
 },
 {
   "id": 47,
   "label": "Wilhelm Ostwald",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Allemagne",
   "nationalite_en": "German",
   "discipline": "Chimie / Radio / Electricité",
   "discipline_en": "Chemistry / Radio / Electricity",
   "description": "Prix Nobel de Chimie en 1909, Wilhelm Ostwald est le créateur de la chimie physique moderne. Défenseur d'une langue auxiliaire internationale, il participe à l'IDO. Il est également artisan de projets bibliographiques en relation avec Otlet autour de \"Die Brücke\".",
   "description_en": "Friedrich Wilhelm Ostwald was a German chemist. He is credited with being one of the modern founders of the field of physical chemistry. He participated in the IDO movement. He was one of the directors of the Die Brücke institute.",
   "image": "img/WOstwald.png",
   "group": "contemporains",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Contemporain",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Wilhelm_Ostwald",
   "date_naissance": "02/09/1853",
   "date_mort": "04/04/1932",
   "gender": "Homme"
 },
 {
   "id": 48,
   "label": "Société d'études sociales et politiques",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie / Politique",
   "discipline_en": "Sociology / Politics",
   "description": "Cette société créée en 1890 par un savant mélange de personnalités progressistes se structure autour d'une bibliothèque, d'un service bibliographique et d'une revue.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 49,
   "label": "Congrès universel de la Paix",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Pacifisme",
   "discipline_en": "Pacifism",
   "description": "Première réalisation du mouvement pacifiste, les Congrès universels de la Paix se réunissent annuellement depuis 1889.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Congr%C3%A8s_universels_pour_la_paix",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 50,
   "label": "Union interparlementaire",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Pacifisme",
   "discipline_en": "Pacifism",
   "description": "Regroupement des parlements souverains, l'UI est une institution internationale politique dont la création est dominée en 1889 par le pacifisme.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Union_interparlementaire",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 51,
   "label": "Revue \"Art moderne\"",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Art",
   "discipline_en": "Art",
   "description": "Cette revue d'art est créée par Edmond Picard, Octave Maus et Emile Verhaeren et est le symbole de l'art social. Véritable expression culturelle et artistique, cette revue est à la pointe de la modernité.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 52,
   "label": "Université nouvelle",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Education",
   "discipline_en": "Education",
   "description": "Née d'une crise démocratique de l'Université de Bruxelles, l'université nouvelle propose un enseignement universitaire gratuit de 1894 à 1919. De cette expérience demeure l'institut des Hautes études de Belgique.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 53,
   "label": "Institut de Sociologie",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Sociologie",
   "discipline_en": "Sociology",
   "description": "En Belgique, la question sociale agite l'élite politique progressiste. L' Institut de sociologie est mis en place sous l'impulsion d'Ernest Solvay. Il s'appuye sur des groupes d'études spécialisés et des semaines sociales.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 54,
   "label": "Bureau International de la Paix",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Pacifisme",
   "discipline_en": "Pacifism",
   "description": "Créé en 1891, le BIP se charge de coordonner l'activité des différentes associations pacifistes.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 55,
   "label": "Institut de Physiologie",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Physiologie",
   "discipline_en": "Physiology",
   "description": "",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 56,
   "label": "Institut de Pédologie",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Pédagogie",
   "discipline_en": "Education",
   "description": "",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 57,
   "label": "Prix Nobel",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "",
   "discipline_en": "",
   "description": "Association créée à l'initiative d'Alfred Nobel, elle attribue chaque année depuis 1901, le prix Nobel de la Paix.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 58,
   "label": "Congrès international des habitations à bon marché",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Prévoyance",
   "discipline_en": "",
   "description": "Le premier congrès est organisé en 1889 à Paris. Par la suite, il se constitue en un comité permanent situé à Bruxelles qui sert de lien entre les acteurs de ce secteur.",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 59,
   "label": "Conseil de Physique",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Physique",
   "discipline_en": "Physics",
   "description": "",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 60,
   "label": "Union de la presse périodique belge",
   "relation_otlet": "",
   "type": "Institution",
   "nationalite": "",
   "nationalite_en": "",
   "discipline": "Presse",
   "discipline_en": "Press",
   "description": "Cette association réunit des professionnels",
   "description_en": "Description traduite",
   "image": "",
   "group": "institution",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Institution",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": ""
 },
 {
   "id": 61,
   "label": "Edouard Otlet",
   "relation_otlet": "Père",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "Transports",
   "discipline_en": "",
   "description": "Père de Paul Otlet. Industriel investi dans les technologies des transports et notamment les tramways, il fait fortune dans l'exploitation du congo belge. toutefois, sa gestion des affaires laisse à désirer. ",
   "description_en": "Paul Otlet's father. He invests in transportation technologies, especially in the development of a Tramway system. His fortune comes from the exploitation of the Belgian Congo.",
   "image": "img/EOtlet.png",
   "group": "famille",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Père de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "1942-06-13 00:00:00",
   "date_mort": "1907-10-20 00:00:00",
   "gender": "Homme"
 },
 {
   "id": 62,
   "label": "Cato Van Nederhesselt",
   "relation_otlet": "Femme",
   "type": "Personne",
   "nationalite": "Belge",
   "nationalite_en": "Belgian",
   "discipline": "",
   "discipline_en": "",
   "description": "Femme de Paul Otlet",
   "description_en": "Paul Otlet's wife",
   "image": "",
   "group": "famille",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Femme de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Femme"
 },
 {
   "id": 63,
   "label": "H.G Wells",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Anglais",
   "nationalite_en": "English",
   "discipline": "Auteur / Anticipation",
   "discipline_en": "Author / Anticipation",
   "description": "HG Wells est intervenu à l'invitation de Paul Otlet pour présenter une réflexion sur un projet de \"cerveau mondial\"",
   "description_en": "HG Wells worked on his \"World Brain\" following Otlet's invitation",
   "image": "img/HGWells.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "",
   "date_naissance": "",
   "date_mort": "",
   "gender": "Homme"
 },
 {
   "id": 64,
   "label": "Nikolaï Roubakine",
   "relation_otlet": "",
   "type": "Personne",
   "nationalite": "Russe",
   "nationalite_en": "Russian",
   "discipline": "Bibliothèque",
   "discipline_en": "Library",
   "description": "Nicolas Roubakine consacre toute sa vie au livre, passion dont il hérite avec une immense bibliothèque de sa mère bibliothécaire. Ses sympathies pour les socialistes-révolutionnaires le poussent à s'expatrier.",
   "description_en": "Nicolas Roubakine consacre toute sa vie au livre, passion dont il hérite avec une immense bibliothèque de sa mère bibliothécaire. Ses sympathies pour les socialistes-révolutionnaires le poussent à s'expatrier.",
   "image": "img/NRoubakine.png",
   "group": "amis",
   "shape": "circularImage",
   "brokenImage": "img/blank.png",
   "relation": "Ami de Paul Otlet",
   "lien_wikipedia": "https://fr.wikipedia.org/wiki/Nikola%C3%AF_Roubakine",
   "date_naissance": "01/07/1862",
   "date_mort": "23/11/1946",
   "gender": "Homme"
 }
]);